import { Hono } from "hono";
import { prisma } from "../index.js";

export const reportRoutes = new Hono();

// This is just a placeholder, since we've already implemented the report endpoints
// in their respective route files (top customers, top menu items, restaurant revenue)
reportRoutes.get("/reports", async (c) => {
  return c.json({
    message: "Available reports",
    reports: [
      "/customers/top - Top 5 customers by number of orders",
      "/menu/top-items - Most ordered menu items across all restaurants",
      "/restaurants/{id}/revenue - Total revenue generated by a restaurant",
    ],
  });
});
